# Queries in the format [domains OR synonyms] AND [interests OR synonyms] AND [keywords]
# Search by specified fields and types
# Domains to retrieve in the search
domains:
- autonomous vehicle
- health
- industry
- smart cities
- multimedia
- science
- robotics
# Technology of interest applied to domains
interests:
  - machine learning
  - artificial intelligence
# Keywords of such applications
keywords:
  - real-world:
    - deploy
    - deployment
    - deployed
    - implemented
    - implementation
    - software
  - reality:
    - deploy
    - deployment
    - deployed
    - implemented
    - implementation
    - software
  - real:
    - deploy
    - deployment
    - deployed
    - implemented
    - implementation
    - software
  - physical world:
    - deploy
    - deployment
    - deployed
    - implemented
    - implementation
    - software
# Search fields
fields:
  - title
  - abstract
types:
  - conferences
  - journals
# Domains and interests can have synonyms
health:
  - healthcare
  - health care
  - health-care
  - medicine
  - medical
  - diagnosis
robotics:
  - robots
  - robot
industry:
  - industry 4
  - manufacture
  - manufacturing
  - factory
  - manufactory
  - industrial
smart cities:
  - sustainable city
  - smart city
  - digital city
  - urban
  - city
  - cities
  - mobility
  - transport
  - transportation system
multimedia:
  - virtual reality
  - augmented reality
  - 3D
  - digital twin
  - video games
  - video
  - image recognition
  - audio
  - speech recognition
  - speech
science:
  - pyshics
  - physicology
  - chemistry
  - biology
  - geology
  - social
  - maths
  - materials
  - astronomy
  - climatology
autonomous vehicle:
  - self-driving vehicle
  - self-driving car
  - autonomous car
  - driverless car
  - driverless vehicle
  - unmanned car
  - unmanned vehicle
  - unmanned aerial vehicle
machine learning:
  - ML
  - deep learning
  - neural networks
  - reinforcement learning
  - supervised learning
  - unsupervised learning
artificial intelligence:
  - AI
databases:
  - ieeexplore
  - springer
  - arxiv
  - sciencedirect
  - scopus
  - core
  - semantic-scholar
  - project-academic